/**
 *
 * $Id$
 */
package SqlMetamodel.validation;

import SqlMetamodel.Column;
import SqlMetamodel.Constraint;
import SqlMetamodel.PrimaryKey;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SqlMetamodel.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateColumn(EList<Column> value);
	boolean validateConstraint(EList<Constraint> value);
	boolean validatePrimaryKey(PrimaryKey value);
}
